# Generated by Django 4.1.5 on 2023-02-01 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_guest_reservation_remove_customer_age_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_type",
                    models.IntegerField(
                        choices=[
                            (0, "Default"),
                            (1, "Single"),
                            (2, "Double"),
                            (3, "Family"),
                        ]
                    ),
                ),
                ("room_number", models.IntegerField(unique=True)),
                ("available", models.IntegerField(choices=[(0, "YES"), (1, "NO")])),
            ],
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="room_number",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="room_type",
        ),
        migrations.AddField(
            model_name="customer",
            name="reservation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="booking.reservation",
            ),
        ),
        migrations.AddField(
            model_name="guest",
            name="room",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="booking.room",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="room",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="booking.room",
            ),
        ),
    ]
