# Generated by Django 4.1.5 on 2023-02-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0006_remove_guest_room_guestdetails_guest_guest_details"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GuestDetails",
            new_name="GuestDetail",
        ),
        migrations.AlterField(
            model_name="room",
            name="room_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
