# Generated by Django 4.1.5 on 2023-02-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0007_rename_guestdetails_guestdetail_alter_room_room_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="details",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
