# Generated by Django 4.1.5 on 2023-02-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0011_alter_room_room_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="available",
            field=models.CharField(
                choices=[("YES", "YES"), ("NO", "NO"), ("PENDING", "PENDING")],
                default="PENDING",
                max_length=10,
                null=True,
            ),
        ),
    ]
