# Generated by Django 4.1.5 on 2023-02-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0012_alter_room_available"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guest",
            name="guest_details",
        ),
        migrations.AlterField(
            model_name="room",
            name="id",
            field=models.IntegerField(
                default=9, max_length=40, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_number",
            field=models.IntegerField(blank=True, unique=True),
        ),
        migrations.DeleteModel(
            name="GuestDetail",
        ),
    ]
