# Generated by Django 4.1.5 on 2023-02-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0013_remove_guest_guest_details_alter_room_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="id",
            field=models.IntegerField(
                default=25, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
