# Generated by Django 4.1.5 on 2023-02-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0018_room_price_invoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
