# Generated by Django 4.1.5 on 2023-02-02 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0022_alter_invoice_room_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="room",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="booking.room",
            ),
        ),
    ]
