# Generated by Django 4.1.5 on 2023-02-02 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0023_guest_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="booking.customer",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="guest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="booking.guest",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
