# Generated by Django 4.1.5 on 2023-02-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0025_alter_invoice_room_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
